### PR TITLE
Fix #179 add process name check to getState

### LINKED ISSUE #179: GetState returns running after host reboot
What could happen is the following:

1. Minishift is started and the driver plugin registers a PID in `~/.minishift/machines/minishift/minishift.pid`
2. The host machine is rebooted (like in case of an update)
3. `minishift status` uses the recorded PID to get the status
4. It finds a running process (note: this is not `xhyve`)
5. `docker-machine` wrongly assumes that the machine instance is active
6. `minishift ssh` therefore will fail to login

Is there a way to make sure the process that is queried for the state is actually related to `xhyve`?

Related issue: https://github.com/minishift/minishift/issues/1066#issuecomment-311552029
Code: https://github.com/zchee/docker-machine-driver-xhyve/blob/master/xhyve/xhyve.go#L316

### PR DESCRIPTION
**Pull request by gbraad**
This fixes #179 by checking the executable name of the process retrieved.

### CODE REVIEW

**Comment by zchee** [comment]
Thanks pull request.
Now I test that fix. Please wait a while.

**Comment by praveenkumar** [comment]
@gbraad Thanks, will also test this out and provide feedback.

**Comment by zchee** [comment]
@gbraad Also, could you add static vendoring `github.com/mitchellh/go-ps`?
We use `gvt`(for now. Maybe I will switch to `dep`), so:

```sh
go get -u -v -x github.com/FiloSottile/gvt
gvt fetch github.com/mitchellh/go-ps
git add vendor/manifest vendor/github.com/mitchellh
```

**Comment by zchee** [comment]
@gbraad And CI are failed. but nevermind. it's caused by OCaml third-party install.

**Comment by praveenkumar** [comment]
> We use gvt(for now. Maybe I will switch to dep)

@zchee what if we can switch to `glide`. we are using it for `minishift` quite  a long time and works as expected. I can help you with migration to glide.

**Comment by zchee** [comment]
@praveenkumar Hm, but glide author?(sdboyer) now maintain golang/dep. And dep command already have [glide importer](https://github.com/golang/dep/blob/master/cmd/dep/glide_importer.go).
But yeah, I think dep is experimental, glide is production ready.
If you really like `glide`, It’s up to you. *switch to glide* pull request is welcome.

**Comment by praveenkumar** [comment]
Tested out this patch and it does work as described only need to put https://github.com/zchee/docker-machine-driver-xhyve/pull/180#issuecomment-311587314 so `make build` doesn't fail.

**Comment by gbraad** [comment]
Thanks @zchee, will do this ASAP

**Comment by zchee** [comment]
@gbraad Thanks. I'll release the new version after check and merge this pull request.
FYI, I tested `minikube` side, it seems works successfully.

**Comment by gbraad** [comment]
so basically you are checking in a fixed version of the library as part of the repositry, under `vendor`

**Comment by gbraad** [comment]
rebased and tested with `minikube` and `minishift`. all OK.

File: xhyve/xhyve.go [hunk 1]
```diff
@@ -329,7 +330,16 @@ func (d *Driver) GetState() (state.State, error) {
 		return state.Stopped, nil
 	}
 
-	return state.Running, nil
+	psproc, err := ps.FindProcess(int(pid))
+	if err != nil {
+		return state.Error, err
+	}
+	// process name is truncated to 'docker-machine-d'
+	if strings.Contains(psproc.Executable(), "docker-machine") {
```
Comment (zchee) [inline xhyve/xhyve.go]: nit: I like *successful return*(? sorry, I'm not good at English) to last `return` statement because of this projects other functions are almost same code style.
So, If you don't mind, could you change logic such as the following code?

```go
if !strings.Contains(psproc.Executable(), "docker-machine") {
	return state.Error, fmt.Errorf("Unable to find 'xhyve' process by PID: %d", pid)
}

return state.Running, nil
```

Comment (zchee) [inline xhyve/xhyve.go]: And, maybe change `Contains` to `HasPrefix` is better?

Comment (gbraad) [inline xhyve/xhyve.go]: I understand what you mean. failing states first (bailout on not meeting a condition, then based on states of the function) and success state at the bottom. ;-) Will do...

Comment (zchee) [inline xhyve/xhyve.go]: If you don't like, I'll approve. it's nit review.

**Comment by gbraad** [comment]
inverted `if` statement to return errors first.

**Comment by zchee** [comment]
@gbraad Thanks!
I'll check and merge it. No reply from Google side, but seems to no problem this change.

**Comment by gbraad** [comment]
they are both (@dlorenc, @r2d4) in a far away timezone. it is likely they will see it in about a few hours. But I always test against `minikube` as we are trying to align with them more. But n their case it is not the default hypervisor.

**Comment by zchee** [comment]
@gbraad I see.
Yes, I also check `minikube` some commands. So already double checked.
I'll merge it. Thanks for contribution.

**Comment by gbraad** [comment]
maybe have some other changes over time, as the PID code should also check for dead/stale PID files. But this is a first improvement!

**Comment by dlorenc** [comment]
Looks great to me, thanks!

**Comment by r2d4** [comment]
LGTM 👍
